name: WTab
version: '${version}'
main: de.theskyscout.wtab.WTab
api-version: 1.20
authors: [ TheSkyScout ]
description: Wolkenlos Tablist Plugin
commands:
  wtab:
    description: Customize the tablist
    aliases: [ tab ]
    usage: /wtab [ create | delete | set | list | exists ]
    permission: wtab.edit